# Generated by Django 3.0.6 on 2021-01-26 09:57

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRecords',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('against', models.CharField(max_length=5, null=True)),
                ('img', django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('key_points', models.CharField(max_length=90000, null=True)),
            ],
        ),
    ]
