# Generated by Django 3.0.5 on 2020-05-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=12, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(max_length=8, null=True)),
                ('age', models.CharField(max_length=3, null=True)),
                ('against_compliants', models.IntegerField(default=0)),
                ('against_challans', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(choices=[('NOC for Employment', 'NOC for Employment'), ('NOC for Immigration', 'NOC for Immigration'), ('NOC for Student', 'NOC for Student')], max_length=30, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('citizen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Cognizable', 'Cognizable'), ('Non Cognizable', 'Non Cognizable'), ('Missing Report', 'Missing Case'), ('Theft Report', 'Theft Case')], max_length=50, null=True)),
                ('citizen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('whom', models.CharField(choices=[('DGP', 'DGP'), ('ADGP', 'ADGP'), ('IGP', 'IGP'), ('DIGP', 'DIGP'), ('SP', 'SP')], max_length=10, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('citizen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.Citizen')),
            ],
        ),
    ]
