# Generated by Django 3.0.5 on 2020-05-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20200512_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen'),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen'),
        ),
        migrations.AlterField(
            model_name='noc',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citizen.Citizen'),
        ),
    ]
