# Generated by Django 3.0.5 on 2020-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_auto_20200512_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
