# Generated by Django 3.0.5 on 2020-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_auto_20200513_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
