# Generated by Django 3.0.5 on 2020-05-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0009_auto_20200513_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Koala.jpg', null=True, upload_to=''),
        ),
    ]
