# Generated by Django 3.0.5 on 2020-05-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0012_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
