# Generated by Django 3.0.6 on 2020-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0014_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='noc',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
