# Generated by Django 3.0.6 on 2020-05-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0015_auto_20200525_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliant',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='static/screenshots/'),
        ),
    ]
