# Generated by Django 3.0.6 on 2021-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0016_compliant_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
